### ISSUE TITLE
在docker中启动就hang住了

### ISSUE THREAD

**Issue by smartlee** [meitu/kvrocks#54]
在main处开始打印 也没有任何输出
gdb 堆栈如下
```
[Switching to thread 1 (Thread 0x7fd29b678300 (LWP 148))]
#0  0x00007fd29ae4d50d in __lll_lock_wait () from /lib64/libpthread.so.0
(gdb) bt
#0  0x00007fd29ae4d50d in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007fd29ae48e5b in _L_lock_883 () from /lib64/libpthread.so.0
#2  0x00007fd29ae48d28 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x00000000005874a9 in malloc_mutex_lock_final (mutex=0xb224e0 <init_lock>) at include/jemalloc/internal/mutex.h:155
#4  je_malloc_mutex_lock_slow (mutex=mutex@entry=0xb224e0 <init_lock>) at src/mutex.c:85
#5  0x00000000005524f0 in malloc_mutex_lock (tsdn=0x0, mutex=0xb224e0 <init_lock>) at include/jemalloc/internal/mutex.h:221
#6  0x000000000040d821 in malloc_init_hard () at src/jemalloc.c:1739
#7  0x0000000000556961 in malloc_init () at src/jemalloc.c:223
#8  imalloc_init_check (sopts=<optimized out>, dopts=<optimized out>) at src/jemalloc.c:2229
#9  imalloc (dopts=<synthetic pointer>, sopts=<synthetic pointer>) at src/jemalloc.c:2260
#10 calloc (num=1, size=32) at src/jemalloc.c:2494
#11 0x00007fd29b05c550 in _dlerror_run () from /lib64/libdl.so.2
#12 0x00007fd29b05c058 in dlsym () from /lib64/libdl.so.2
#13 0x00007fd29b25fbbc in sysconf (name=name@entry=30) at libsysconfcpus.c:108
#14 0x00000000005881a6 in os_page_detect () at src/pages.c:429
#15 je_pages_boot () at src/pages.c:600
#16 0x000000000040d756 in malloc_init_hard_a0_locked () at src/jemalloc.c:1518
#17 0x000000000040d882 in malloc_init_hard () at src/jemalloc.c:1750
#18 0x000000000055575d in malloc_init () at src/jemalloc.c:223
#19 imalloc_init_check (sopts=<optimized out>, dopts=<optimized out>) at src/jemalloc.c:2229
#20 imalloc (dopts=<synthetic pointer>, sopts=<synthetic pointer>) at src/jemalloc.c:2260
#21 je_malloc_default (size=16) at src/jemalloc.c:2289
#22 0x00007fd29a350ecd in operator new(unsigned long) () from /lib64/libstdc++.so.6
#23 0x00007fd29a820c27 in google::FlagRegisterer::FlagRegisterer<std::string>(char const*, char const*, char const*, std::string*, std::string*) () from /lib64/libgflags.so.2.2
#24 0x00007fd29a8143b3 in _GLOBAL__sub_I_gflags.cc () from /lib64/libgflags.so.2.2
#25 0x00007fd29b471973 in _dl_init_internal () from /lib64/ld-linux-x86-64.so.2
#26 0x00007fd29b46315a in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#27 0x0000000000000001 in ?? ()
#28 0x00007ffdce76a93c in ?? ()
#29 0x0000000000000000 in ?? ()
```

strace 如下
```
arch_prctl(ARCH_SET_FS, 0x7f0ef453d300) = 0
mprotect(0x7f0ef2c94000, 16384, PROT_READ) = 0
mprotect(0x7f0ef2eb3000, 4096, PROT_READ) = 0
mprotect(0x7f0ef31b5000, 4096, PROT_READ) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f0ef453a000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f0ef4539000
mprotect(0x7f0ef349f000, 32768, PROT_READ) = 0
mprotect(0x7f0ef36d2000, 4096, PROT_READ) = 0
mprotect(0x7f0ef3f1a000, 4096, PROT_READ) = 0
mprotect(0x7f0ef38f4000, 4096, PROT_READ) = 0
mprotect(0x7f0ef3afa000, 4096, PROT_READ) = 0
mprotect(0x7f0ef3d02000, 4096, PROT_READ) = 0
mprotect(0x7f0ef4122000, 4096, PROT_READ) = 0
mprotect(0x7f0ef4325000, 4096, PROT_READ) = 0
mprotect(0xb0d000, 8192, PROT_READ)     = 0
mprotect(0x7f0ef4548000, 4096, PROT_READ) = 0
munmap(0x7f0ef4543000, 15371)           = 0
set_tid_address(0x7f0ef453d5d0)         = 223
set_robust_list(0x7f0ef453d5e0, 24)     = 0
rt_sigaction(SIGRTMIN, {0x7f0ef3d0a820, [], SA_RESTORER|SA_SIGINFO, 0x7f0ef3d135f0}, NULL, 8) = 0
rt_sigaction(SIGRT_1, {0x7f0ef3d0a8b0, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x7f0ef3d135f0}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
getrlimit(RLIMIT_STACK, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
futex(0x7f0ef34bb8ac, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x7f0ef34bb8b8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
readlink("/etc/malloc.conf", 0x7ffe7608c6e0, 4096) = -1 ENOENT (No such file or directory)
futex(0x7f0ef41230b0, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0xb22580, FUTEX_WAIT_PRIVATE, 2, NULL^Cstrace: Process 223 detached
 <detached ...>
```

**Comment by git-hulk** [comment]
这个看起来是 gflags 在分配内存的时候 jemalloc 死锁了，麻烦帮忙执行：
```
thread apply all bt
```
提供一下完整的堆栈，然后可以尝试把 docker 基础镜像中的 gflags 依赖库去掉

**Comment by smartlee** [comment]
只有一个线程 想不通死锁是哪里来的  gflags 依赖库 怎么去除？
```
(gdb) thread apply all bt

Thread 1 (Thread 0x7fd29b678300 (LWP 148)):
#0  0x00007fd29ae4d50d in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007fd29ae48e5b in _L_lock_883 () from /lib64/libpthread.so.0
#2  0x00007fd29ae48d28 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x00000000005874a9 in malloc_mutex_lock_final (mutex=0xb224e0 <init_lock>) at include/jemalloc/internal/mutex.h:155
#4  je_malloc_mutex_lock_slow (mutex=mutex@entry=0xb224e0 <init_lock>) at src/mutex.c:85
#5  0x00000000005524f0 in malloc_mutex_lock (tsdn=0x0, mutex=0xb224e0 <init_lock>) at include/jemalloc/internal/mutex.h:221
#6  0x000000000040d821 in malloc_init_hard () at src/jemalloc.c:1739
#7  0x0000000000556961 in malloc_init () at src/jemalloc.c:223
#8  imalloc_init_check (sopts=<optimized out>, dopts=<optimized out>) at src/jemalloc.c:2229
#9  imalloc (dopts=<synthetic pointer>, sopts=<synthetic pointer>) at src/jemalloc.c:2260
#10 calloc (num=1, size=32) at src/jemalloc.c:2494
#11 0x00007fd29b05c550 in _dlerror_run () from /lib64/libdl.so.2
#12 0x00007fd29b05c058 in dlsym () from /lib64/libdl.so.2
#13 0x00007fd29b25fbbc in sysconf (name=name@entry=30) at libsysconfcpus.c:108
#14 0x00000000005881a6 in os_page_detect () at src/pages.c:429
#15 je_pages_boot () at src/pages.c:600
#16 0x000000000040d756 in malloc_init_hard_a0_locked () at src/jemalloc.c:1518
#17 0x000000000040d882 in malloc_init_hard () at src/jemalloc.c:1750
#18 0x000000000055575d in malloc_init () at src/jemalloc.c:223
#19 imalloc_init_check (sopts=<optimized out>, dopts=<optimized out>) at src/jemalloc.c:2229
#20 imalloc (dopts=<synthetic pointer>, sopts=<synthetic pointer>) at src/jemalloc.c:2260
#21 je_malloc_default (size=16) at src/jemalloc.c:2289
#22 0x00007fd29a350ecd in operator new(unsigned long) () from /lib64/libstdc++.so.6
#23 0x00007fd29a820c27 in google::FlagRegisterer::FlagRegisterer<std::string>(char const*, char const*, char const*, std::string*, std::string*) () from /lib64/libgflags.so.2.2
#24 0x00007fd29a8143b3 in _GLOBAL__sub_I_gflags.cc () from /lib64/libgflags.so.2.2
#25 0x00007fd29b471973 in _dl_init_internal () from /lib64/ld-linux-x86-64.so.2
#26 0x00007fd29b46315a in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#27 0x0000000000000001 in ?? ()
#28 0x00007ffdce76a93c in ?? ()
#29 0x0000000000000000 in ?? ()
```

**Comment by git-hulk** [comment]
这个类似: https://github.com/jemalloc/jemalloc/issues/1318 ，不过最终认为是标准库的问题。如果是 centos 那么可以通过 yum erase， ubuntu 就通过 apt 来 uninstall

**Comment by smartlee** [comment]
去掉了对gflags的依赖 还是卡住了 
```
(gdb) thread 1
[Switching to thread 1 (Thread 0x7f0780441300 (LWP 82))]
#0  0x00007f077fe1a50d in __lll_lock_wait () from /lib64/libpthread.so.0
(gdb) bt
#0  0x00007f077fe1a50d in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007f077fe15e5b in _L_lock_883 () from /lib64/libpthread.so.0
#2  0x00007f077fe15d28 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x0000000000586699 in malloc_mutex_lock_final (mutex=0xb21380 <init_lock>) at include/jemalloc/internal/mutex.h:155
#4  je_malloc_mutex_lock_slow (mutex=mutex@entry=0xb21380 <init_lock>) at src/mutex.c:85
#5  0x00000000005516e0 in malloc_mutex_lock (tsdn=0x0, mutex=0xb21380 <init_lock>) at include/jemalloc/internal/mutex.h:221
#6  0x000000000040d271 in malloc_init_hard () at src/jemalloc.c:1739
#7  0x0000000000555b51 in malloc_init () at src/jemalloc.c:223
#8  imalloc_init_check (sopts=<optimized out>, dopts=<optimized out>) at src/jemalloc.c:2229
#9  imalloc (dopts=<synthetic pointer>, sopts=<synthetic pointer>) at src/jemalloc.c:2260
#10 calloc (num=1, size=32) at src/jemalloc.c:2494
#11 0x00007f077e9f8550 in _dlerror_run () from /lib64/libdl.so.2
#12 0x00007f077e9f8058 in dlsym () from /lib64/libdl.so.2
#13 0x00007f0780028bbc in sysconf (name=name@entry=30) at libsysconfcpus.c:108
#14 0x0000000000587396 in os_page_detect () at src/pages.c:429
#15 je_pages_boot () at src/pages.c:600
#16 0x000000000040d1a6 in malloc_init_hard_a0_locked () at src/jemalloc.c:1518
#17 0x000000000040d2d2 in malloc_init_hard () at src/jemalloc.c:1750
#18 0x000000000055494d in malloc_init () at src/jemalloc.c:223
#19 imalloc_init_check (sopts=<optimized out>, dopts=<optimized out>) at src/jemalloc.c:2229
#20 imalloc (dopts=<synthetic pointer>, sopts=<synthetic pointer>) at src/jemalloc.c:2260
#21 je_malloc_default (size=29) at src/jemalloc.c:2289
#22 0x00007f077f53fecd in operator new(unsigned long) () from /lib64/libstdc++.so.6
#23 0x00007f077f59ea19 in std::string::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&) () from /lib64/libstdc++.so.6
#24 0x00007f077f5a02a1 in char* std::string::_S_construct<char const*>(char const*, char const*, std::allocator<char> const&, std::forward_iterator_tag) () from /lib64/libstdc++.so.6
#25 0x00007f077f5a06d8 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&) () from /lib64/libstdc++.so.6
#26 0x000000000042c8ed in __static_initialization_and_destruction_0 (__initialize_p=1, __priority=65535) at redis_metadata.h:33
#27 0x000000000042cb52 in _GLOBAL__sub_I__ZNK6Engine14MetadataFilter6FilterEiRKN7rocksdb5SliceES4_PSsPb () at compact_filter.cc:172
#28 0x00000000007e570d in __libc_csu_init ()
#29 0x00007f077ec1d495 in __libc_start_main () from /lib64/libc.so.6
#30 0x000000000042b45d in _start ()
```

**Comment by smartlee** [comment]
jemalloc 编译时修改 --with-jemalloc-prefix=je_ 解决问题

**Comment by git-hulk** [comment]
依赖包会自动安装 jemalloc, 镜像不需要再编译安装
